
import fr.utbm.e.systemeexpert.modele.Equation;
import fr.utbm.e.systemeexpert.modele.Hypotheses;
import fr.utbm.e.systemeexpert.modele.Systeme;
import java.util.ArrayList;
import fr.utbm.e.systemeexpert.modele.Principal;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author U563081
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        this.setResizable(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       countPre = 1;
        access();

    }

    public void access() {
        btnNbPremisse.setVisible(false);
        txtNbPremisse.enable(false);
        btnValPremisse.setVisible(false);
        txtPremisse.enable(false);
        txtResultat.enable(false);
        btnResultat.setVisible(false);
        txtHypothese.enable(false);
        btnHypothese.setVisible(false);
        btnExecuter.enable(false);
        lblSystem.enable(false);
        btnNbSystem.setVisible(true);
        txtAreaSystem.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNbSysteem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNbPremisse = new javax.swing.JTextField();
        btnNbSystem = new javax.swing.JButton();
        btnNbPremisse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtResultat = new javax.swing.JTextField();
        btnValPremisse = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPremisse = new javax.swing.JTextField();
        btnResultat = new javax.swing.JButton();
        txtHypothese = new javax.swing.JTextField();
        btnHypothese = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        countPremisse = new javax.swing.JLabel();
        getCountPremisse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblHypothese = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblSystem = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSystem = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblHypotheseFinal = new javax.swing.JLabel();
        btnExecuter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnNouveau = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notion de système Expert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(jLabel1)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Entrez le nombre d'équation du système");
        jLabel9.setName(""); // NOI18N

        txtNbSysteem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNbSysteem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNbSysteemActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 51, 204));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Entrez le nombre de premise de l'équation");

        txtNbPremisse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNbPremisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNbPremisseActionPerformed(evt);
            }
        });

        btnNbSystem.setBackground(new java.awt.Color(102, 153, 255));
        btnNbSystem.setIcon(new javax.swing.ImageIcon("C:\\Users\\u563081\\Desktop\\Cours P20\\SI73\\Projetsystemeexpert\\SystemeExpert\\icon.jfif")); // NOI18N
        btnNbSystem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNbSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNbSystemActionPerformed(evt);
            }
        });

        btnNbPremisse.setIcon(new javax.swing.ImageIcon("C:\\Users\\u563081\\Desktop\\Cours P20\\SI73\\Projetsystemeexpert\\SystemeExpert\\icon.jfif")); // NOI18N
        btnNbPremisse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNbPremisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNbPremisseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Premise ");

        txtResultat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnValPremisse.setIcon(new javax.swing.ImageIcon("C:\\Users\\u563081\\Desktop\\Cours P20\\SI73\\Projetsystemeexpert\\SystemeExpert\\icon.jfif")); // NOI18N
        btnValPremisse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnValPremisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValPremisseActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Hypothèse(s) initiale(s)");

        txtPremisse.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnResultat.setIcon(new javax.swing.ImageIcon("C:\\Users\\u563081\\Desktop\\Cours P20\\SI73\\Projetsystemeexpert\\SystemeExpert\\icon.jfif")); // NOI18N
        btnResultat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultatActionPerformed(evt);
            }
        });

        txtHypothese.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHypothese.setIcon(new javax.swing.ImageIcon("C:\\Users\\u563081\\Desktop\\Cours P20\\SI73\\Projetsystemeexpert\\SystemeExpert\\icon.jfif")); // NOI18N
        btnHypothese.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHypothese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypotheseActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Résultat");

        countPremisse.setText("1");

        getCountPremisse.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHypothese))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(60, 60, 60)
                        .addComponent(txtResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHypothese, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNbPremisse, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtNbSysteem)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(getCountPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPremisse)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnValPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNbSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNbPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNbSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtNbSysteem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtNbPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(countPremisse))
                    .addComponent(btnNbPremisse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getCountPremisse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(btnResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txtHypothese, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHypothese, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 610, 280));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("S=");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Hypothèses initiales =   ");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 232, -1, 30));

        lblHypothese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(lblHypothese, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, 30));

        lblSystem.setColumns(20);
        lblSystem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSystem.setRows(5);
        jScrollPane1.setViewportView(lblSystem);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 380, 70));

        txtAreaSystem.setColumns(20);
        txtAreaSystem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAreaSystem.setRows(5);
        jScrollPane2.setViewportView(txtAreaSystem);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 370, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 490, 280));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hypothèses finales = ");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 230, 30));

        lblHypotheseFinal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHypotheseFinal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHypotheseFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHypotheseFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 670, 120));

        btnExecuter.setBackground(new java.awt.Color(0, 153, 102));
        btnExecuter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExecuter.setForeground(new java.awt.Color(255, 255, 255));
        btnExecuter.setText("Exécuter");
        btnExecuter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExecuter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuterActionPerformed(evt);
            }
        });
        getContentPane().add(btnExecuter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 110, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 180, 90, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 180, 90, 40));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 70, 50));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 14, 40, 30));

        btnNouveau.setBackground(new java.awt.Color(153, 153, 255));
        btnNouveau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnNouveau.setText("Nouveau");
        btnNouveau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });
        getContentPane().add(btnNouveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNbPremisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNbPremisseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNbPremisseActionPerformed

    private static int nbSystem;
    private int nbPremiss;
    private int getCountPre = 1;
    private int countPre = 1;
    private String getUniqueEquation = "";
    private Equation tabEquation[];
    private Systeme s = new Systeme(new ArrayList<Equation>());
    Hypotheses h = new Hypotheses(new ArrayList<String>());


    private void btnNbSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNbSystemActionPerformed

        try {
            nbSystem = Integer.parseInt(txtNbSysteem.getText());
            tabEquation = new Equation[nbSystem];
            btnNbPremisse.setVisible(true);
            txtNbPremisse.enable(true);
            txtNbSysteem.enable(false);
            btnNbSystem.setVisible(false);
             //JOptionPane.showMessageDialog(this, "Vous devez entrer un nombre valide !"+tabEquation.length);
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Vous devez entrer un nombre valide !");
        }


    }//GEN-LAST:event_btnNbSystemActionPerformed

    public static void main(String[] args) {
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }
    
   

    //Equation e1 = new Equation(new ArrayList<String>());
    // Validation des premisse
    private void btnValPremisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValPremisseActionPerformed
        // TODO add your handling code here:
        //txtPremisse.enable(false);
        //btnValPremisse.enable(false);
        // btnResultat.enable(true);
        //txtResultat.enable(true);        
        if (nbPremiss > getCountPre) {
            tabEquation[countPre-1].getPremisses().add(txtPremisse.getText());
            getUniqueEquation += txtPremisse.getText() + "^";
            lblSystem.setText(getUniqueEquation);
            txtPremisse.setText("");
            getCountPre++;
            getCountPremisse.setText(getCountPre + "");
        } else if (nbPremiss == getCountPre) {
            tabEquation[countPre-1].getPremisses().add(txtPremisse.getText());
            getUniqueEquation += txtPremisse.getText() + "";

            lblSystem.setText(getUniqueEquation);

            countPremisse.setText(countPre + "");
            txtPremisse.setText("");

            txtPremisse.enable(false);
            btnValPremisse.setVisible(false);
            btnResultat.setVisible(true);
            txtResultat.enable(true);
            getCountPremisse.setText("1");
        }

    }//GEN-LAST:event_btnValPremisseActionPerformed

    private void btnNbPremisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNbPremisseActionPerformed

        try {
            nbPremiss = Integer.parseInt(txtNbPremisse.getText());
            btnNbPremisse.setVisible(false);
            txtNbPremisse.enable(false);
            txtPremisse.enable(true);
            btnValPremisse.setVisible(true);
            tabEquation[countPre-1] = new Equation();        
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Vous devez entrer un nombre valide !");
        }


    }//GEN-LAST:event_btnNbPremisseActionPerformed

    private void btnResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultatActionPerformed
        // TODO add your handling code here:
        getCountPre = 1;
        txtNbPremisse.setText("");
        btnResultat.setVisible(false);
        if (nbSystem > countPre) {

            btnNbPremisse.setVisible(true);
            txtNbPremisse.enable(true);
            txtPremisse.enable(false);
            btnValPremisse.setVisible(false);
            countPre++;
            tabEquation[countPre-1] = new Equation();        
            countPremisse.setText(countPre + "");
            //btnResultat.enable(false);
            txtResultat.enable(false);

            getUniqueEquation += " => " + txtResultat.getText() + "";
            txtAreaSystem.append("\n");
            txtAreaSystem.append(getUniqueEquation);
            lblSystem.setText("");
            //int a =countPre-2;
          //  JOptionPane.showMessageDialog(this, "Vous devez entrer un nombre valide ! "+a);
            tabEquation[countPre-2].setResultat(txtResultat.getText());
            
            s.addEquation(tabEquation[countPre-2]);
            getUniqueEquation="";
            txtAreaSystem.append(getUniqueEquation);

            txtResultat.setText("");

        } else if (nbSystem == countPre) {
            
            getUniqueEquation += " => " + txtResultat.getText() + "";
            txtAreaSystem.append("\n");
            txtAreaSystem.append(getUniqueEquation);
            tabEquation[countPre-1].setResultat(txtResultat.getText());
             s.addEquation(tabEquation[countPre-1]);
             lblSystem.setText("");
            getUniqueEquation="";
            
            txtResultat.enable(false);

            txtHypothese.enable(true);
            btnResultat.setVisible(false);
            btnHypothese.setVisible(true);
            txtResultat.setText("");
        }

    }//GEN-LAST:event_btnResultatActionPerformed
    private void btnHypotheseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypotheseActionPerformed
        // TODO add your handling code here:
        h.addHypothese(txtHypothese.getText());        
        lblHypothese.setText(h.toString());
        btnExecuter.setVisible(true);
        txtHypothese.setText("");
    }//GEN-LAST:event_btnHypotheseActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        // TODO add your handling code here:

        txtNbPremisse.setText("");
        txtPremisse.setText("");
        txtResultat.setText("");
        txtHypothese.setText("");
        lblSystem.setText("");
        lblHypotheseFinal.setText("");
        lblHypothese.setText("");
        txtNbSysteem.enable(true);
        txtAreaSystem.setText("");
        countPremisse.setText("1");
        getCountPremisse.setText("1");
        s = new Systeme(new ArrayList<Equation>());
        h = new Hypotheses(new ArrayList<String>());
        getCountPre = 1;
        countPre = 1;
        access();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnExecuterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuterActionPerformed
        // TODO add your handling code here:
        Principal.doOperation(h, s);
        lblHypotheseFinal.setText(h.toString());
        btnHypothese.setVisible(false);
    }//GEN-LAST:event_btnExecuterActionPerformed

    private void txtNbSysteemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNbSysteemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNbSysteemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecuter;
    private javax.swing.JButton btnHypothese;
    private javax.swing.JButton btnNbPremisse;
    private javax.swing.JButton btnNbSystem;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnResultat;
    private javax.swing.JButton btnValPremisse;
    private javax.swing.JLabel countPremisse;
    private javax.swing.JLabel getCountPremisse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHypothese;
    private javax.swing.JLabel lblHypotheseFinal;
    private javax.swing.JTextArea lblSystem;
    private javax.swing.JTextArea txtAreaSystem;
    private javax.swing.JTextField txtHypothese;
    private javax.swing.JTextField txtNbPremisse;
    private javax.swing.JTextField txtNbSysteem;
    private javax.swing.JTextField txtPremisse;
    private javax.swing.JTextField txtResultat;
    // End of variables declaration//GEN-END:variables
}
